-- ruta para las imagenes public_html/img/img_cards/
-- insert into linea_del_tiempo values(0,"aaaa-mm-dd","Titulo","Descripcion","img1","img2","img3","url_video");
-- insert into linea_del_tiempo values(0,"","","","","","",""); 

insert into linea_del_tiempo values(0,"1935-01-01","Seleccion del Plantel","El ingeniero Bátiz como jefe del DETIC, eligió una antigua construcción en la calle de Mar Mediterráneo 227, para establecer la Escuela de Preaprendizaje núm. 3, antecedente académico de este CECyT, cuyos talleres eran de Electricidad, de Carpintería, y los de Hojalatería y de Ajuste.","","","","");
insert into linea_del_tiempo values(0,"1935-06-01", "Inicio de la Escuela de Preaprendizaje No. 3","Se nombro primer Director al Ing. Francisco J. del Collado e Illanes, designado por el Ing. Juan de Dios Bátiz Paredes. En su primer semestre 114 aspirantes fueron inscritos para la segunda mitad de 1935 formando 4 grupos de primer año. Esta escuela se inició con el horario de 8 a 14 horas donde se instruían las materias de Aritmética y Geometría, Dibujo, Legislación del Trabajo, Higiene, Historia, Castellano y Geografía; y por la tarde en el horario de 16 a 20 horas se impartían los talleres de Carpintería, Hojalatería, Electricidad y Herrería.","public_html/img/img_cards/imgTimeline1-1.png","","","");
insert into linea_del_tiempo values(0,"1936-01-01", "Fundación del Instituto Politécnico Nacional","El General Lázaro Cárdenas del Rio con la finalidad de atender en forma más específica las necesidades técnico-industriales que el país requería, su tarea primordial sería la de generar ingenieros y técnicos en áreas especializadas que fortalecieran el desarrollo de la nación. Por ello el Instituto toma un gran impulso y la demanda de la juventud por ingresar a sus espacios crece de manera exponencial. Estando al frente del Departamento de Enseñanza Técnica, el ingeniero Juan de Dios Bátiz, con el apoyo del presidente Lázaro Cárdenas,  trabajó en una institución que se encargara de la educacion técnica en México, dando origen al Instituto Politécnico Nacional.","public_html/img/img_cards/imgTimeline2-1.png","public_html/img/img_cards/imgTimeline2-2.png","","");
insert into linea_del_tiempo values(0,"1936-01-02","Inicio de las actividades del IPN","El general Lázaro Cárdenas informó el inicio de las actividades del IPN, siendo Juan de Dios Bátiz el primer Director General. Durante ese año la Prevocacional 3 crea su primer reglamento.","","","","");
insert into linea_del_tiempo values(0,"1937-09-01","Desigancion del director RODOLFO UZETA RAMOS ","Al concluirse la licencia otorgada al ingeniero del Collado, el ingeniero Juan de Dios Bátiz Paredes quien fungía como jefe del Departamento de Enseñanza Superior Técnica Industrial y Comercial en ese momento, lo designó. La creciente demanda de ingreso aumentó en 1937 casi al doble, con una inscripción de 421 alumnos; fue necesaria la primera obra de ampliación que se realizó en la escuela.","","","","");
insert into linea_del_tiempo values(0,"1938-01-01","Optimizacion de Talleres","Esta escuela desarrolló una educación técnica formal apoyada en el nuevo y moderno equipo recibido. Se instaló un laboratorio de Biología. Para los talleres de Ajuste y Hojalatería se adquirieron modernos taladros mecánicos. El taller de Carpintería fue dotado de una mandriladora y una sierra circular, tres tornos, un escoplo. En el taller de Electricidad se sustituyeron los antiguos sistemas de tableros por los de casetas, en las cuales los alumnos ejecutaban sus trabajos individualmente. También se construyó un departamento especial para la enseñanza de instalaciones eléctricas ocultas ","","","","");
insert into linea_del_tiempo values(0,"1938-01-01","Surgen los Fogoneros Infernales", "Lo que en ese entonces era la Prevocacional 3 se convirtio en la casa de un equipo de Futbol Americano: Los Fogoneros Infernales, que hasta en su nombre deportivo reflejan algo de su particular idiosincrasia: Fogoneros, por la cercanía de los edificios al paso del Ferrocarril de Cuernavaca, cuyo silbato madrugador, servia de despertador a los habitantes de los sótanos; e Infernales, tal vez porque, para mucha gente, la forma de ser y el comportamiento de los jugadores del Equipo era verdaderamente infernal.  Su primer entrenador, José Alvarado de la Tejera","public_html/img/img_cards/imgTimeline3-1.png","","","");
insert into linea_del_tiempo values(0,"1939-06-05","Designacion del director interino ALEJANDRO GUILBOT SERRANO","El profesor Guilbot Serrano fungía como secretario de la Escuela Pre- vocacional núm.3, cuando por motivo de la licencia concedida al ingeniero Uzeta, cubrió en forma económica el cargo de director del plantel. En esas condiciones el profesor Guilbot cumplió su función en espera de que la Comisión Nacional de Escalafón le adjudicara la plaza en propiedad.","","","","");
insert into linea_del_tiempo values(0,"1940-01-01","Restructuracion del plan de estudios en Escuelas Prevocacionales"," Al restructurarse el Departamento de Enseñanza Técnica Industrial y Comercial, el plan de estudios de las Escuelas Prevocacionales cambió de dos a tres años. También se instituyó la primera Sociedad de Padres de Familia. Al final de la década de los cuarenta, nuestra escuela acogió en su inicio a los dos primeros grupos de la Vocacional que alimentaría a la Escuela Superior de Ingeniería Química e Industrias Extractivas, hoy CECyT “Estanislao Ramírez Ruiz.”","","","","");
insert into linea_del_tiempo values(0,"1940-02-01","Designacion del director PEDRO ALVARADO LANG","Con fecha 1 de febrero de 1940 el ingeniero Pedro Alvarado Lang fue designado director de la Escuela Prevocacional núm. 3, razón de su traslado desde Puebla, donde asumía la Dirección de la Escuela Prevocacional tipo A núm. 9 de Teziutlán.","","","",""); 
insert into linea_del_tiempo values(0,"1942-01-16","El Servicio Educativo Militar","Al verse involucrado el país en la Segunda Guerra Mundial, se instituyó el Servicio Educativo Militar. La SEP, por conducto de la Dirección de Segunda Enseñanza dispuso que un día a la semana se impartiera instrucción militar a los alumnos de las escuelas dependientes de ella. Los alumnos que no cumplieran con ese servicio serían dados de baja de la escuela. Además de los alumnos, algunos profesores y empleados se sumaron a las filas de la instrucción militar instaurada.","","","",""); 
insert into linea_del_tiempo values(0,"1943-08-07","Designacion del director interino JOSÉ JUÁREZ SÁNCHEZ","Al haberse aceptado la permuta de plazas entre el ingeniero Alvarado Lang y el ingeniero Noé Gómez, recibió el ingeniero Lang la comunicación del jefe del Departamento de Prevocacionales para que le entregara al ingeniero Juárez Sánchez la Dirección de esta escuela ","","","",""); 
insert into linea_del_tiempo values(0,"1943-09-14","Designacion del Director NOÉ GÓMEZ RODRÍGUEZ","Fue asignado a la dirección de la Escuela Prevocacional núm. 3 el 1 de agosto de 1943, aunque asumió dicha dirección hasta su llegada a México, el 14 de septiembre del mismo año","","","","");
insert into linea_del_tiempo values(0,"1944-04-18","De la SEP al IPN", "La SEP pasa el control técnico-administrativo de las prevocacionales 1, 2, 3, 4 y 5 del DF al IPN. En el año de 1944 las escuelas prevocacionales pasaron a ser escuelas tecnológicas. Fue así como la Prevocacional núm. 3 se convirtió en Escuela Tecnológica núm. 3, sin perder por ello su vinculación con el IPN. Sus nuevos planes de estudio de tres años eran equivalentes a los de segunda enseñanza con los enfoques formativos que se requerían para el desarrollo industrial del país en ese momento. Al darse los cambios necesarios para la evolución de la educación vinculada orgánicamente al IPN.","public_html/img/img_cards/imgTimeline4-1.png","public_html/img/img_cards/imgTimeline4-2.png","","");
insert into linea_del_tiempo values(0,"1944-06-15","Designacion del director interino FRANCISCO CAMPOS Y CAMPOS","Cuando el ingeniero Noé Gómez solicitó su licencia laboral fue asignado director del plantel en septiembre de 1943. Algún tiempo después el entonces director general del IPN el doctor Sandoval Vallarta, lo nombró director sustituto el 15 de junio de 1944, oficializando con ese nombramiento la función que había empezado a desempeñar con anterioridad","","","",""); 
insert into linea_del_tiempo values(0,"1944-10-10","Designacion del director BALTAZAR MENDOZA CERVANTES","Fue designado director  de la entonces llamada Escuela Tecnológica núm. 3, en sustitución del ingeniero Noé Gómez Rodríguez90 a quien de manera interina y por muy corto tiempo había reemplazado el ingeniero Campos y Campos","","","",""); 
insert into linea_del_tiempo values(0,"1948-01-02","Escuela Tecnologica 3", "Escuelas prevocacionales pasaron a ser escuelas tecnológicas. Fue así como la Prevocacional núm. 3 se convirtió en Escuela Tecnológica núm. 3, sin perder por ello su vinculación con el IPN. Sus nuevos planes de estudio de tres años eran equivalentes a los de segunda enseñanza con los enfoques formativos que se requerían para el desarrollo industrial del país en ese momento.","","","","");
insert into linea_del_tiempo values(0,"1948-08-01","Designacion del Director FRANCISCO J. CALDERÓN BARQUÍN "," El Director General del IPN determinó seleccionar para hacerse cargo de la dirección de este plantel, a una persona externa que no tuviera simpatías o antipatías entre la comunidad, de ese modo recayó tal designación en el profesor Francisco J. Calderón Barquín a quien se le consideró el indicado para sustituir al profesor Mendoza. Por tal motivo el 31 de julio de 1948 fue la fecha en que el profesor Calderón fue comisionado por el ingeniero Alejandro Guillot para atender la administración de la Escuela Tecnológica núm. 3","","","","");
insert into linea_del_tiempo values(0,"1950-08-02","Respaldo de la comunidad al director","Con el reciente descontento de la comundad con paros y suspensiones laborales colminaron con la renuicia del Director General Alejandro Guillot, se aprovecho la situacion para atacar a el profesor Calderón por identificarlo como amigo personal del ingeniero Guillota, el profesor Calderón solicitó al ingeniero Manuel Ramírez Carraza recién nombrado director del IPN, su cambio de adscripción con el propósito de evitar acciones que lesionaran la buena marcha de la escuela, la comunida por medio del secretario general de la Sociedad de Alumno enviaron un oficio al director general del IPN en el que le solicitaban respetuosamente que le fuera rechazada su renuncia al profesor Calderón,provocando que el director general le pidiera al profesor Calderón que permaneciera en su puesto hasta nueva orden","","","",""); 
insert into linea_del_tiempo values(0,"1952-02-16","Desingacion del director ALFONSO LOZANO BERNAL","El ingeniero Juan Manuel Ramírez Carraza director general del IPN, le comunicó al ingeniero Lozano Bernal que, con un nuevo nombramiento de director de Enseñanza Tecnológica, se haría cargo de la Escuela Tecnológica núm. 3.","","","","");
insert into linea_del_tiempo values(0,"1952-04-01","Inicio de Obras de transformacion del edificio","Se iniciaron obras de transformación del edificio, como los nuevos salones de Dibujo y el Taller de Hojalatería, y se instaló el laboratorio de Física. Se iniciaron actividades artísticas, culturales y deportivas que contribuyeron en la formación integral del estudiante. En esa misma etapa se acondicionó la antigua capilla y se le dio funcionalidad como sala de proyecciones documentales para ser usada por los estudiantes.","","","","");
